# ==============================
# üß© application-dev.yml (local)
# ==============================
spring:
  jpa:
    hibernate:
      ddl-auto: none    # Verifica que el esquema coincide con las entidades, sin modificarlo
    show-sql: true          # Muestra SQL en consola
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true  # A√±ade comentarios en el SQL con el nombre de la entidad
  liquibase:
    enabled: true
# Configuraci√≥n de logs detallados para depuraci√≥n de SQL y bindings
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
