# ================================================
# üß© application-dev.yml ‚Äî Configuraci√≥n para H2 (Desarrollo)
# ================================================
spring:
  datasource:
    url: jdbc:h2:mem:imperial_database;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE  # Base de datos en memoria
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  jpa:
    hibernate:
      ddl-auto: none  # Desactiva la generaci√≥n autom√°tica de esquemas (Liquibase se encarga)
    show-sql: true  # Muestra el SQL generado en la consola
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true  # A√±ade comentarios en el SQL generado
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true  # Permite acceso remoto a la consola (solo para desarrollo)
  liquibase:
    enabled: true  # Activa Liquibase para migraciones

logging:
  level:
    org.hibernate.SQL: debug  # Muestra el SQL generado
    org.hibernate.type.descriptor.sql.BasicBinder: trace  # Muestra los valores de los par√°metros en el SQL
    org.springframework.security: DEBUG  # Logs detallados de Spring Security
    org.springframework.web: DEBUG  # Logs detallados de Spring Web
    org.hibernate: ERROR  # Solo muestra errores de Hibernate
