# ===========================
# üåç application.yml (Base)
# ===========================
spring:
  application:
    name: hotel
  profiles:
    active: dev  # Perfil activo por defecto
  jpa:
    open-in-view: false  # Desactiva OpenSessionInView para evitar LazyInitializationException
    properties:
      hibernate:
        format_sql: true  # Formatea el SQL generado para mejor legibilidad
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml  # Ubicaci√≥n del changelog de Liquibase
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
springdoc:
  swagger-ui:
    display-operation-id: false
    display-request-duration: false
    filter: false
    deep-linking: false
    doc-expansion: none
    try-it-out-enabled: true
    show-extensions: false
    show-common-extensions: false
