# ===================
# üåç application.yml
# ===================
spring:
  application:
    name: hotel
  profiles:
    active: dev

  jpa:
    # Propiedades comunes de JPA
    open-in-view: false     # Evita LazyInitializationException por mal uso en controladores
    properties:
      hibernate:
        format_sql: true    # Aplica formato legible al SQL generado

  # Configuraci√≥n de Liquibase (migraciones)
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

springdoc:
  swagger-ui:
    display-operation-id: false
    display-request-duration: false
    filter: false
    deep-linking: false
    doc-expansion: none
    try-it-out-enabled: true
    show-extensions: false
    show-common-extensions: false
